title: MAMA AR, VR og 360
author: MAMA
email: mama@mamacph.dk
description: >-
  Digitale interaktive oplevelser. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
permalink: pretty

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus
  - jekyll-coffeescript

# Use this for production
sass:
  style: :compressed
sass:
  sass_dir: _sass/ar

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]